### ISSUE TITLE
Depth peeling does not work anymore

### ISSUE THREAD

**Issue by fvichot** [medInria/medInria-public#215]
When depth peeling is activated, it does nothing. Also, it should be moved out of the mesh navigator and moved into the vtkViewNavigator, as it applies to fibers as well, and in general anything rendered with polygons.

**Comment by ocommowi** [comment]
Well, I just tested and it does work for me on head data meshes in medinria data. At least, it does something good on those. Do you have an example data that used to work and works differently ?

**Comment by fvichot** [comment]
Apparently, it's a new driver problem... so far, it doesn't work on nvidia drivers on Linux, either on F16 or F19, but works on intel on linux or mac, with or without software rendering. If anyone has a Nvidia on Mac, I'd be curious to know if it works.

**Comment by fvichot** [comment]
Just tested on Macleod, which has an ATI GPU, and it doesn't work either...

**Comment by mikejbuckingham** [comment]
So the "correct" fix for this is to do depth sorting, but this introduces a number of problems in our pipeline.

First, vtk's depth-sorting can only be performed on a single mesh, and in order to get the correct behaviour we'll have to create a unified mesh from all layers, then perform depth sorting on that mesh before rendering. This makes handling opacity problematic, as we're now operating on a single mesh (with a single property) rather than each layer having its own properties.

Secondly, because the depth-sorting is obviously subject to camera angles, the algorithm is run each frame. This is prohibitively expensive in terms of performance.

As this appears to stem from a driver issue rather than a problem in our code specifically, I'm recommending we don't try to fix it on our side, but rather wait for the drivers to be fixed.

**Comment by mikejbuckingham** [comment]
Extra info : Just tested on a Mac with an nVidia GPU, works fine.

**Comment by mikejbuckingham** [comment]
So the vtk code has this fantastic little snippet :
else if(isATI)
{
    this->DepthPeelingIsSupported = 0;
}

So I guess we'll not be providing depthpeeling on ATI cards anytime soon! I'll add a tooltip to state that depth peeling doesn't work on all architectures.

Still no idea why nvidia doesn't work yet.

**Comment by fvichot** [comment]
OK, so this is fixed in #223: apparently onnvidia GPUs an some others, you can't change SetAlphaBitPlanes() and SetMultiSamples() after the first render. It so happens that on Intel, alpha bits are enabled by default, so we could still do depth rendering (MultiSamples to 0 is not necessary for depth peeling, it just destroys your performance if it's not). So I moved that code back to the medVtkView constructor, it's now enabled by default. Multisampling being 0 by default improves performance a bit when opacity is on, with or without depth peeling, and possibly in other areas, I haven't run extensive testing. This is the way it used to be before the view refactoring, so I don't expect this will cause any problems.
