### ISSUE TITLE
dev branch comments

### ISSUE THREAD

**Issue by papadop** [medInria/medInria-public#283]
No comment yet on the refactoring... Just a couple of side questions on the branch:
- cmake 3.2 is required... Is this really needed ?? There are a lot of computers out there with 3.0. If 3.2 has an important feature why not, but this should be discussed in advance.
- cloning of external modules is done under the build directory. While this may make sense for modules we do not intend to change (VTK, ITK), this is more worrying for DCMTK, RPI, TTK or DTK which we may need to change. The prospect of loosing work just because a rm -rf of the build directory is too high for me. I vote for sources going with sources like it was with the previous superproject...
- cloning of ITK fails:
  "FAILED: cd /user/papadop/home/compiles/medInria-dev-linux-f21/superbuild/src && /usr/bin/cmake -P /user/papadop/home/compiles/medInria-dev-linux-f21/superbuild/tmp/ITK-gitclone.cmake &&    /usr/bin/cmake -E touch /user/papadop/home/compiles/medInria-dev-linux-f21/superbuild/src/ITK-stamp/ITK-download
  -- Had to git clone more than once:
            3 times.
   CMake Error at /user/papadop/home/compiles/medInria-dev-linux-f21/superbuild/tmp/ITK-gitclone.cmake:40 (message):
   Failed to clone repository: 'git://itk.org/ITK.git'"
  Do not understand why as doing it by hand works... Changing git: into https: does not work better. This was with cmake 3.0.2 or cmake-3.4-rc3, so probably not cmake related...
- cloning of DCMTK and VTK is strange as they report that clones are in detached state...

So for now, I'm stucked...

**Comment by ocommowi** [comment]
RP is not here for some days so I'll answer based on what I know, good luck with that :)

- I think it's cmake 3.2 because some functions of cmake he is using are documented only from that version. I don't remember which ones though, sorry.
- I agree on your second point that having sources inside the build dir is disturbing and makes them difficult to find. RP would answer that this is how cmake works and superprojects are not made for developing in them, just to be a nice framework to compile everything to make a release. I tend to agree with that point of view, but still I like having sources in the src dir. Anyway, if that's the only disagreement point on this branch, this will be easy to settle.
- I remember having problems with that ITK repo when I was on the wifi in Sophia and some other times too. I would suggest going for the one on github which is much more reliable (https://github.com/InsightSoftwareConsortium/ITK). It's updated only every night but that's enough for us. Don't hesitate to commit a change on that
- For those two repos, RP is using tags and not branches in the superproject definitions. So they end up in detached state. For DCMTK, it's related to the fact that Alex (Abadie, yes he's back :) ) has updated qtdcm to use qt5, which is nice but requires this specific dcmtk tag. For VTK, I don't know, we could use the release branch instead

**Comment by rdebroiz** [comment]
> cmake 3.2 is required... Is this really needed ?? There are a lot of computers out there with 3.0. If 3.2 has an important feature why not, but this should be discussed in advance.

I think the most "advance" CMake feature I used is [CMAKE_CXX_STANDARD](https://cmake.org/cmake/help/v3.1/variable/CMAKE_CXX_STANDARD.html)
It seems to become available with CMake 3.1.3 (thought it was 3.2 i don't know why)

> cloning of external modules is done under the build directory 

I see your point about having them in the build is not so good, but i don't like having them in the sources either because it poluate it. I add a CMake variable to let the dev choose where he wants to have it. I put the default value in the source, under a `thirdparts` folder. I let you change that default value if you don't like it. see #284 

> cloning of DCMTK and VTK is strange as they report that clones are in detached state...

No it is normal, it's because we are checking a tag rather than a branch, which is the same as checking a specific commit. It's already the case for [VTK](https://github.com/medInria/medinria-superproject/blob/master/cmake/externals/projects_modules/VTK.cmake). 

About DCMTK I switch to the official repository. It is needed for the QtDCM Qt5 compatible version. it also avoid us to have to install it to be able to found it from CMake. It also allow to get rid of some link related fixes on OSX. I let you see more details [here](https://github.com/medInria/medInria-public/pull/279).

> For VTK, I don't know, we could use the release branch instead

The thing is that the release branch provided by Kitware are more release-candidate branches where new things are pushed on a regular basis. It happened that it doesn't compile anymore and it could bring some bugs. IMO we should always use tagged version for all thirdparts libraries.
