### ISSUE TITLE
Pixel value in view always linked to first layer

### ISSUE THREAD

**Issue by ocommowi** [medInria/medInria-public#318]
The pixel value in a layered view of medinria is always linked to the first layer. Even if the second layer of a view is selected. 

Example: 
- drop the 3D T1 image from Head_Data
- drop the Moteur_Droit image (same folder) on the same view
- select the upper most layer on the right (Moteur_Droit)
- move the mouse over the image, the pixel value annotation displays the values of the first layer

**Comment by Florent2305** [comment]
This bug takes place into VtkImageView.cxx line 1150 on the function GetValueAtPosition.
m_poInternalImageFromInput is not the good reference or is not updated on change layer.
This bug is due to refactoring of SetInputData->SetInputConnection and/or refactoring about medVtkImageInfo, but more probably the 1st refactoring.
