### ISSUE TITLE
Bugs and remark about version 3.0

### ISSUE THREAD

**Issue by alegouhy** [medInria/medInria-public#319]
1. Can't access network drive when browsing directory to open and export data.
2. The browsing window is not the same when opening or exporting data.

Remarks: the right panel is about 1.5 times wider than in medinria 2.x

on Windows 10.0.15063

**Comment by alegouhy** [comment]
After rebooting the app, the network drive is now detected.

**Comment by ocommowi** [comment]
Network drives and other usb keys shown are given by qt which relies on the system and we don't have so much control on that part. So I guess there is not much we can do on it. But if you see them now, that's great !

I know that the open and export windows are different. It's due to the fact that we had to change some properties of the export window and as such it is not exactly like the open window. something to look at though.

I'm surprised by your remark on the right panel, is it the one of visualization ? On mac, I don't see any difference between medinria 2.2.3 and 3.0. Which medinria 2.x are you comparing to ?

**Comment by alegouhy** [comment]
It's between 2.2.3 and 3.0. Not only in visualization, in all workspaces.

Also the minimum size of the window is quite big ( more than 2/3 of the screen in length and width ). Therefore when doing [win]+[right] ( resp [left] ) in windows which is supposed to resize and move the current window such as it covers the half right part of the screen, it makes something wider than expected.

**Comment by ocommowi** [comment]
J'ai remis 800x600 en taille par defaut. Le reste est bon ?

**Comment by Florent2305** [comment]
Sans remarques de plus je clos l'issue.
