### ISSUE TITLE
Improve Home page ergonomics and style

### ISSUE THREAD

**Issue by Florent2305** [medInria/medInria-public#446]
- Min H/V size
- Logo position
- Elements positions

**Comment by mathildemerle** [comment]
I was thinking about this ergonomic enhancement, and decided to do a **quick** drawing in order to explain.

_This is my chef-d'oeuvre, my fabulous art masterpiece, with great skills, as you can see :D. Behold!_
_(Do not let me alone with Gimp or Paint haha)_

![VisuSuggestion](https://user-images.githubusercontent.com/3910352/67097344-2fd1cb00-f1ba-11e9-9f2c-7462090034c5.png)

Anyway, this is a serious suggestion, i'm going to detail it:
 * I've always thought that there are too many "buttons areas", specially on the homepage. I never know how to call them: "settings buttons under the description on homepage", "buttons on the bottom right of the application in a bar" , etc. 
 * My idea is to fuse almost all of them in a top bar menu, which can be accessed from every workspace (as the Composer menu right now).
 * Help, Log, About, and the other buttons could be important to be accessible from the workspaces.
 * The workspaces access menu from the bottom is split into 2 menu items "Areas" (previous "Basic") and "Workspaces". It's clearer when we speak with users.
 * Previous "settings buttons under the description" can open a window if needed in the menu.
 * There is a lot of workspaces, the "Methodology" list is too long. It's why in the drawing it's split automatically in several smaller column on homepage.
 * medInria logo and descriptions are vertically positioned at the top of homepage, and below there are the areas/workspaces columns. It allows to leave more room to potential new columns (for external projects or not).

Other ideas:
 * Close button at bottom right of the app: can it be removed? There is already a native close button in the application. Idem for Fullscreen button?
 * "Close" and "Fullscreen" could be put in the menu bar if needed, with "screenshot" and "Adjust container".
 * Visualization workspace could perhaps be in the Workspaces column? Maybe in first position in bold font.
 * The quick access menu "Search a toolbox" tool could be added in a Tools button in the menu?
 * The Log item could deploy 2 items, one which already exists opening the logs directory, and the other opening a potential logs windows? The Log system could be improved through that.
 * Could the "Browser" item menu be renamed "Files"? This is more common in application. Users seems to have a hard time finding the area to import data.
 
These are really just suggestions for the future. They are based on some problems that i have with the application ergonomy, but other solutions could be found to solve them.
:)

**Comment by mathildemerle** [comment]
A small idea in addition: the Adjust Container Size button could be in the Tools button in views.

**Comment by ocommowi** [comment]
Hey there. The idea sounds nice but I would like not to lose too much vertical space on small screens. So I would suggest to get rid of the status bar if we go toward this (and since it is flagged 4.1, let's rethink the whole thing). I would thus move the icons currently on the status bar somewhere in the menus (to be adapted depnding on the os by the way, eg the fullscreen mode being already handled by macos). 

Where everything is in the menus has to be defined. One thing to check : I am not sure that on mac you can have menu icons (I would say no). So yes let's move them in sub-menus with shortcuts.

A final thing: if we remove the status bar, we should get the process messages currently in it reworked, cf my issue #448

**Comment by mathildemerle** [comment]
It could indeed be interesting to remove or reshape the status bar. 
In addition to the discussion, there is currently a shared progress bar (medProgressionStack) in medAbstractWorkspaceLegacy. It means that each toolbox in a medAbstractWorkspaceLegacy workspace (mostly medSelectorWorkspace) can use this progression stack to show progression, or success/failure bar. So, in toolboxes, the status bar is mostly used to display occasionally error messages, and as far as i see the remaining common messages are from the database (saved/imported data from the toolbox). We could enhance that for 4.1 indeed :)

**Comment by mathildemerle** [comment]
Cf an issue from @msermesant (2015) https://github.com/medInria/medInria-public/issues/282 asking to rename/enhance also the Browser area.

**Comment by mathildemerle** [comment]
An enhancement suggestion in the view & layer settings tools:

 * Link view properties and Link layer properties are not really understood by users. It would be better to put them in the same toolbox, and maybe rename them. 
 * A specific problem: in the "Mesh Manipulation" toolbox, you can use several meshes, and if you want to move/rotate them together, you need to link the properties through the "Link view properties:" button which hold the Orientation and Position, but not the "Link layer properties" whereas the meshes are "layers" in a same view.
