### ISSUE TITLE
first TTK compilation : freeze the computer

### ISSUE THREAD

**Issue by nbaraka** [medInria/medInria-public#654]
It is not the first time I got this. 
But during its compilation on ubuntu18 it freezes the computer. (just yesterday after a pull from master) 

I got to force the shutdown by keeping off the power button.

**Comment by mathildemerle** [comment]
:o i have never seen that, except if i use too much processors compiling. On my computer, i use `make -j8`, but as we discussed with @Florent2305 i could use a higher number, but my computer then lag/freezes a bit too much. I prefer to compile at a lower level, and i can use the computer during the compilation. Which number are you using?

**Comment by mathildemerle** [comment]
By the way, for everyone, because of the changes of this week (addition of plugins, changes in external projects in https://github.com/medInria/medInria-public/pull/604 and https://github.com/medInria/medInria-public/pull/650), we need to compile one time from the superproject (your "build" root), not from QtCreator or an other IDE compiling only the medInria sources.

**Comment by nbaraka** [comment]
-j15 but it has not been an issue for other source code but only for ttk. I have done in December few ttk compilations and got the same pb. It seems really related to the compilator. It can make the compilator to crash :)

**Comment by mathildemerle** [comment]
impossible to redo the problem, and we are not anymore on ubuntu 18
