### ISSUE TITLE
Registration WS "adjustable wrench" icone don't respond without Image

### ISSUE THREAD

**Issue by Florent2305** [medInria/medInria-public#696]
Into Registration workspace, the "adjustable wrench" icone has no action without image into the view.
It's a big problem because a user can want open an image via this icone.

**Comment by mathildemerle** [comment]
In Filtering and Registration, the goal was to have fix containers, that's why the "Tools" button was disabled (but it would be better to display a gray icon then) as far as i remember. That's because we are not used to use the Open button in the Tools menu.

But then if you add a data, the right behavior appears: you can use the Tools button, but can't split or remove the views.

So, indeed there is a problem, and i would add 2 problems to solve. Summary of "Tools" menu issues:

 * In Filtering and Registration, we need to enable by default the Tool menu, but on "no split" mode, like when we add a data.
 * Add a right disabled Tools icon.
 * If you add a data in Registration for instance, you can Maximize it. If you remove it and add it back, you can't Maximize it. Choose if we want to be able to maximize or not in "no split" mode.
