### ISSUE TITLE
medDatabaseImporter::ensureUniqueSeriesName prevents duplicate series names even between unrelated studies or patients

### ISSUE THREAD

**Issue by fcollot** [medInria/medInria-public#820]
When importing new data in `medAbstractDatabaseImporter::importData`, the function `medDatabaseImporter::ensureUniqueSeriesName` is called. In that function, if the series name of the new data already exists anywhere in the database, then a prefix is added to it. This constraint should have been limited to the same study.

This is an issue with `medAbstractDatabaseImporter::importData`, not `medAbstractDatabaseImporter::importFile`, and so will only appear when data is imported from within medInria (output of a toolbox for example). You can reproduce this by creating a new data inside medInria (from any toolbox). While it is still a temporary data, rename it to a series name that already exists in the DB (from a different patient). Now save the new data, and it will have a prefix added to it.

**Comment by mathildemerle** [comment]
Tested, i can see at some cases. Between each test case, this is needed to remove each study used:

### Import of multiple studies with "saved in the database" import
 * Import study A with series aa and bb
 * Import study B with series aa and bb
 * -> there is no suffixes to aa or bb. This behavior seems fine because it can happen to have data with the same name in separated studies and it's not a problem

### Removal of a series
 * Import study A with series aa and bb -> remove aa

Then you have two cases:
 * Import study A with series aa and bb, or just aa -> the data is called "aa" -> no problems
 * Temporary import of aa -> the data us called "aa_1" even if there is only 1 "aa" data in the study :no_entry_sign: 

### Moving data from one study to an other
 * Import study A with series aa and bb
 * Import study C with a data
 * Move aa to C

Then you have two cases:
 * Import aa in A -> aa is called aa, no problems
 * Temporary Import aa in A -> save -> aa is called "aa_1" whereas the original aa has been moved to C :no_entry_sign: 

### Outputs from toolbox
 * Import A with aa and bb -> rename bb in "aa (painted)"
 * Draw a ROI on aa in PaintToolBox for instance and use the "Save" button in the tlbx -> a temporary "pact (painted)" data  is created
 * Save the temporary data -> it's called "pact (painted)_1" which is fine

### Outputs with data in an other study
 * Import study A with series aa and bb
 * Import study B with series aa and bb
 * Rename aa in B as "aa (painted)"
 * Draw a ROI on aa from A in PaintToolBox for instance and use the "Save" button in the tlbx -> a temporary "pact (painted)" data  is created
 * Save the temporary data -> it's called "pact (painted)_1" which is NOT fine, since the false painted one is in B :no_entry_sign: 

It could be a problem with the import or saving of temporary data.

**Comment by fcollot** [comment]
Just to clarify, when I say it involves imports from inside medInria, I mean when data is imported through `medDataManager::importData`, which is what happens when you save temporary data, and so why it appears in all the tests where that is done.
